### ISSUE TITLE
Question re. errors

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/optimus-py#32]
I gave OptimusPy a try today, but I run into errors at the end. 
Any idea what could be wrong? Am I missing a package or something (I did check requirements.txt)? 

Completed analysis for cube '011_PnL'
Updated dimension order for cube '011_PnL' to ['Function_PL', 'Cost_element', 'Data_source', 'Reporting_entity', 'Currency', 'Product_group', 'Period', 'Version_Master', 'PnL_measure']
Traceback (most recent call last):
  File "C:/TM1py/tm1py-samples-master/optimus-py-master/optimuspy.py", line 253, in <module>
    output=cmd_args.output)
  File "C:/TM1py/tm1py-samples-master/optimus-py-master/optimuspy.py", line 197, in main
    RESULT_PATH / RESULT_PNG.format(cube_name, view_name, TIME_STAMP))
  File "C:\TM1py\tm1py-samples-master\optimus-py-master\results.py", line 166, in to_png
    plt.savefig(file_name, dpi=400)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 88, in print_figure
    super().print_figure(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 521, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 407, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 392, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'results\\011_PnL_Optimus_2020-12-02_19-09-39.png'

**Comment by MariusWirtz** [comment]
Hi @hermie64,

I was able to replicate the error. Currently, optimus fails if the results-foder doesn't exist.
For now, you can just create a results folder manually.

I will create a fix for Optimus so that it creates the folder autonomously

**Comment by hermie64** [comment]
Thanks @MariusWirtz
