### ISSUE TITLE
Incorrect Padding Error

### ISSUE THREAD

**Issue by StreetRodRacer** [cubewise-code/optimus-py#42]
I installed TM1py and MatPlotLib, tested the Check.py script to ensure that I can connect to my environment. I also updated the CONFIG.ini file to match my environment and ran the code and received the following error code:

```
c:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\optimus-py-master>python optimuspy.py -i="tm1" -v="Global_Balance Sheet Trend - ACT" -e="10" -f="False" -o="csv" -u=True
Starting. Arguments retrieved from cmd: Namespace(instance_name='tm1', view_name='Global_Balance Sheet Trend - ACT', executions='10', fast='False', output='csv', update='True', password=None, process_name=None)
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\optimus-py-master\optimuspy.py", line 276, in <module>
    success = main(
  File "c:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\optimus-py-master\optimuspy.py", line 134, in main
    with TM1Service(**tm1_args) as tm1:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\TM1Service.py", line 15, in __init__
    self._tm1_rest = RestService(**kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 200, in __init__
    self._start_session(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 354, in _start_session
    self.b64_decode_password(password) if decode_b64 else password,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 442, in b64_decode_password
    return b64decode(encrypted_password).decode("UTF-8")
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

I tested the code against other views and received the same issue. Is this related to a cloud implementation of TM1/PA?

Thank you in advance!

**Comment by MariusWirtz** [comment]
Hi @StreetRodRacer,

When you provide the connection parameters like this:
```
address=10.77.19.60
port=8983
user=Admin
password=YXBwbGU=
decode_b64=True
ssl=True`
```

the password needs to be b64 encoded.
If you don't mind a plain password in the config.ini you can implement the config.ini like this:

```
address=10.77.19.60
port=8983
user=Admin
password=apple
decode_b64=False
ssl=True`
```
