### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by jimnaff** [cubewise-code/optimus-py#6]
Hello, trying to run this with a small view but see this error:

2020-08-26 13:56:59,417 - optimuspy - INFO - Starting. Arguments retrieved from cmd: Namespace(cube_name='TestCube', executions='5', instance_name='tm1srv01', max_permutations='5', measure_dimension_only_numeric=1, mode='Best', view_names='view1')
2020-08-26 13:57:01,726 - optimuspy - ERROR - Fatal error
Traceback (most recent call last):
  File "optimuspy.py", line 76, in main
    permutation_results += original_order.execute()
  File "C:\Cubewise\optimus-py-master\executors.py", line 90, in execute
    return [self._evaluate_permutation(self.original_dimension_order, retrieve_ram=True)]
  File "C:\Cubewise\optimus-py-master\executors.py", line 53, in _evaluate_permutation
    ram_usage = self._retrieve_ram_usage()
  File "C:\Cubewise\optimus-py-master\executors.py", line 68, in _retrieve_ram_usage
    value = self.tm1.cubes.cells.execute_mdx_values(mdx=mdx)[0]
TypeError: 'generator' object is not subscriptable

**Comment by jimnaff** [comment]
Also noticed that the MDX  in the executors.py file for the perf cube is:

SELECT  
            {{ [}}PerfCubes].[{}] }} ON ROWS,
            {{ [}}StatsStatsByCube].[Total Memory Used] }} ON COLUMNS
            FROM [}}StatsByCube]
            WHERE ([}}TimeIntervals].[LATEST)

It appears the Right bracket is missing for LATEST, however the MDX seems to still work.

**Comment by MariusWirtz** [comment]
Hi @jimnaff ,

It's a compatibility issue between TM1py and Optimus.
I addressed the issue earlier today. Please download the latest version of optimus and try again.

If it does not help please upgrade tm1py to the last version here on GitHub:
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`

Thanks for the catch on the MDX. I will fix this. Surprisingly TM1 doesn't seem to mind the error though.

**Comment by jimnaff** [comment]
Thanks Marius. It is completing successfully now, thank you. One more thing, I do not see the results. If I am understanding the code, does it suppose to create a 'results' folder?  If it supposed to, I am not seeing that folder nor the csv and png files.

**Comment by MariusWirtz** [comment]
Strange. Did it write an error message into the log ?

**Comment by jimnaff** [comment]
Here's the log file content ( I added some logging.info calls to get mdx and filename):
2020-08-26 17:20:08,542 - optimuspy - INFO - Starting. Arguments retrieved from cmd: Namespace(cube_name='bpc.Plan Summary', executions='1', instance_name='tm1srv01', max_permutations='1', measure_dimension_only_numeric='1', mode='All', view_names='view1')
2020-08-26 17:20:15,650 - optimuspy - INFO - 
            SELECT  
            { [}PerfCubes].[bpc.Plan Summary] } ON ROWS,
            { [}StatsStatsByCube].[Total Memory Used] } ON COLUMNS
            FROM [}StatsByCube]
            WHERE ([}TimeIntervals].[LATEST])
            
2020-08-26 17:20:15,716 - optimuspy - INFO - Sparsity ratio for dimension 'Version': 0.00
2020-08-26 17:20:15,771 - optimuspy - INFO - Sparsity ratio for dimension 'Organization': 0.00
2020-08-26 17:20:16,751 - optimuspy - INFO - Sparsity ratio for dimension 'Accounts Master': 0.00
2020-08-26 17:20:16,953 - optimuspy - INFO - Sparsity ratio for dimension 'Fiscal Period': 0.00
2020-08-26 17:20:16,997 - optimuspy - INFO - Sparsity ratio for dimension 'bpc.Plan Summary Measure': 0.00
2020-08-26 17:20:16,997 - optimuspy - INFO - Determined One Shot order: '['bpc.Plan Summary Measure', 'Version', 'Organization', 'Fiscal Period', 'Accounts Master']'
2020-08-26 17:21:47,134 - optimuspy - INFO - ExecutionMode.BRUTE_FORCE 100 % done. 1 iterations completed
2020-08-26 17:30:21,748 - optimuspy - INFO - Analysis Completed
2020-08-26 17:30:21,749 - optimuspy - INFO - More details in csv and png files in results folder
2020-08-26 17:30:21,750 - optimuspy - INFO - filename: results\bpc.Plan Summary_view1_2020-08-26_17-20-08.csv
2020-08-26 17:30:22,273 - optimuspy - INFO - Reestablishing original dimension order
2020-08-26 17:31:09,386 - optimuspy - INFO - Finished successfully

**Comment by MariusWirtz** [comment]
It looks like the files were created successfully.

Perhaps it has something to do with relative paths and absolute paths. Are
you executing it from a different folder ? Has the results folder perhaps
been created somewhere else?

**Comment by jimnaff** [comment]
Also, don't know what this means but the command line returns this message:

C:\Cubewise\optimus-py-master\python.exe optimuspy.py -i="tm1srv01"
  -c="TestCube" -v="view1" -e="1" -p="1" -m="All" -n=1
__C:\Cubewise\optimus-py-master\results.py:114: UserWarning: FixedFormatter should only be used together with FixedLocator
  plt.gca().set_xticklabels(['{:.0f}%'.format(x * 100) for x in plt.gca().get_xticks()])__

**Comment by jimnaff** [comment]
found them!  my mistake, thank you for your help!
